# Generated by Django 5.2 on 2025-04-18 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_categoria_generousuario_nombrecomuna_rolusuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='comuna',
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.nombreregion'),
        ),
        migrations.DeleteModel(
            name='NombreComuna',
        ),
    ]
